name: Android Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: Run tests
      run: gradle test --stacktrace
      continue-on-error: true

    - name: Run lint
      run: gradle lint --stacktrace
      continue-on-error: true

    - name: Build debug APK
      run: gradle assembleDebug --stacktrace

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: simple-live-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Upload lint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-results
        path: app/build/reports/lint-results-*.html
        retention-days: 7

  build-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: Build release APK
      run: gradle assembleRelease --stacktrace

    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: simple-live-release
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 90
